server:
  port: 8090
  address: 0.0.0.0

spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3360}/${MYSQL_DATABASE:loans}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true